### ISSUE TITLE
Correction / addition "Centralized Exchanges"

### ISSUE THREAD

**Issue by stakecube** [blocknetdx/documentation#13]
https://docs.blocknet.co/project/exchanges/

StakeCube URL needs to be changed to: https://stakecube.net/app/exchange/BLOCK_BTC

Additional pairs: 
SCC: https://stakecube.net/app/exchange/BLOCK_SCC
LTC: https://stakecube.net/app/exchange/BLOCK_LTC
DASH: https://stakecube.net/app/exchange/BLOCK_BTC

**Comment by HanniAbu** [comment]
Thanks! We've included them in this commit: 
https://github.com/blocknetdx/documentation/commit/c360edd4810ea2948c708faedd767328f21d7712

This will be published today and merged into master later this week
