### ISSUE TITLE
Updated exchanges

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/documentation#19]
title: Blocknet (BLOCK) Exchanges
description: Blocknet's utility token, BLOCK, can be traded on various exchanges and different types of  exchanges, each with different advantages and disadvantages.

# Exchanges
Blocknet's utility token, [BLOCK](/blockchain/introduction), can be purchased and sold in several ways, each with different advantages and disadvantages. This list is provided for informational purposes only. Services listed here have not been evaluated or endorsed by Blocknet. Please exercise discretion when using third-party services.

---

## Centralized Exchanges
Centralized exchanges are one of the most popular ways to trade cryptocurrency. Some serve different markets, some are in direct competition, some have cheaper fees, and some are subject to more or less strict regulatory requirements. They are operated by a single company, which may be obliged by the laws of the jurisdiction in which it operates to collect data on its customers.The following options are available:

Exchange        | Market        | Link
----------------|---------------|------
Bittrex Global  | (BTC/BLOCK)   | [Buy Now](https://global.bittrex.com/Market/Index?MarketName=BTC-BLOCK)
DigiFinex       | (BTC/BLOCK)   | [Buy Now](https://www.digifinex.vip/en-ww/trade/BTC/BLOCK)
DigiFinex       | (USDT/BLOCK)  | [Buy Now](https://www.digifinex.vip/en-ww/trade/USDT/BLOCK)
StakeCube       | (BTC/BLOCK)   | [Buy Now](https://stakecube.net/app/exchange/BLOCK_BTC)
StakeCube       | (LTC/BLOCK)   | [Buy Now](https://stakecube.net/app/exchange/BLOCK_LTC)
StakeCube       | (SCC/BLOCK)   | [Buy Now](https://stakecube.net/app/exchange/BLOCK_SCC)
StakeCube       | (DASH/BLOCK)  | [Buy Now](https://stakecube.net/app/exchange/BLOCK_DASH)
Altilly         | (BTC/BLOCK)   | [Buy Now](https://www.altilly.com/market/BLOCK_BTC)

---

## Decentralized Exchanges
Decentralized exchanges are purely peer-to-peer instead of requiring a trusted entity to manage the transaction. This is the most secure form of trading. The following options are available:

* [__Block DX__](/blockdx/setup)
    * [View Open Orders](https://blockdx.co/orders)
    * [View Trade History](https://blockdx.co/trade-history)
    * [View Exchange Volume](https://blockdx.co/charts)

---

**Comment by ConanMishler** [comment]
Exchanges Updated in draft & master branches
