### ISSUE TITLE
Typo in SNode setup - fail2ban section

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/documentation#66]
After running the auto builder tool, the cmd for getting the log path is: `docker inspect exrproxy-env-xr_proxy-1 | grep '"LogPath":'`

The docs show this as the cmd to run: `docker inspect exrproxy-env_xr_proxy_1 | grep '"LogPath":'`

**To do:**
For point #30 of https://docs.blocknet.co/service-nodes/setup/#deploy-enterprise-xrouter-environment - fail2ban section:
[ ] - change `exrproxy-env_xr_proxy_1` to `exrproxy-env-xr_proxy-1`

**Comment by ConanMishler** [comment]
This was fixed.
